# Generated by Django 2.2.3 on 2023-07-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
            preserve_default=False,
        ),
    ]
