# Generated by Django 2.2.3 on 2023-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230718_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='description',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='option',
            name='answer',
        ),
        migrations.AddField(
            model_name='option',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
