# Generated by Django 2.2.3 on 2023-07-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PimlurMOOC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PimlurItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_content_html', models.TextField()),
                ('video_content_html', models.TextField()),
                ('quiz_content_html', models.TextField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pimlur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PimlurMOOC.Pimlur')),
                ('pimlurSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PimlurMOOC.PimlurSubCategory')),
            ],
        ),
    ]
