# Generated by Django 2.2.3 on 2023-07-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0002_pimluritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimlurcategory',
            name='pimlur',
        ),
        migrations.AddField(
            model_name='pimlur',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PimlurMOOC.PimlurCategory'),
            preserve_default=False,
        ),
    ]
