# Generated by Django 2.2.3 on 2023-07-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0004_pimluruser_pimlurcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimluruser',
            name='PimlurCategory',
        ),
        migrations.AddField(
            model_name='pimlur',
            name='pimlurCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pimlurCategory', to='PimlurMOOC.PimlurCategory'),
            preserve_default=False,
        ),
    ]
