# Generated by Django 2.2.3 on 2023-07-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0006_auto_20230716_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimlursubcategory',
            name='pimlur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PimlurMOOC.Pimlur'),
            preserve_default=False,
        ),
    ]
