# Generated by Django 3.2.20 on 2023-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0008_auto_20230718_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimluritem',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
