# Generated by Django 2.2.3 on 2023-07-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0008_auto_20230718_2032'),
        ('PimlurMOOC', '0008_auto_20230716_1952'),
    ]

    operations = [
    ]
