# Generated by Django 3.2.20 on 2023-07-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PimlurMOOC', '0009_merge_20230719_0007'),
        ('PimlurMOOC', '0009_pimluritem_allow_comments'),
    ]

    operations = [
    ]
